apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: wallet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: "traceqlEditor"
            - name: GF_INSTALL_PLUGINS
              value: "grafana-exploretraces-app"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: config
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: config
          configMap:
            name: observability-config
            items:
              - key: grafana-datasources.yaml
                path: datasources.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: wallet-app
spec:
  ports:
    - port: 3000
  selector:
    app: grafana