apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: wallet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:latest
          args:
            - "-config.file=/etc/loki/loki-config.yaml"
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
      volumes:
        - name: config
          configMap:
            name: observability-config
            items:
              - key: loki-config.yaml
                path: loki-config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: wallet-app
spec:
  ports:
    - port: 3100
  selector:
    app: loki
