apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: wallet-app
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: default
      containers:
        - name: promtail
          image: grafana/promtail:latest
          args:
            - "-config.file=/etc/promtail/promtail-config.yaml"
          ports:
            - name: http-metrics
              containerPort: 9080
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: observability-config
            items:
              - key: promtail-config.yaml
                path: promtail-config.yaml
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
---
apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: wallet-app
spec:
  selector:
    app: promtail
  ports:
    - name: http-metrics
      port: 9080
      targetPort: 9080
