apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: wallet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest
          args:
            - "--config.file=/etc/tempo/tempo.yaml"
          ports:
            - containerPort: 3200 # HTTP
            - containerPort: 4317 # gRPC
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
            - name: tempo-storage
              mountPath: /var/tempo
      volumes:
        - name: config
          configMap:
            name: observability-config
            items:
              - key: tempo.yaml
                path: tempo.yaml
        - name: tempo-storage
          persistentVolumeClaim:
            claimName: tempo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: wallet-app
spec:
  ports:
    - name: http
      port: 3200
    - name: otlp-grpc
      port: 4317
  selector:
    app: tempo
